import type { GameState, Mods } from "../data/types.js";

export function createInitialMods(): Mods {
  return {
    pawnSideStep: false,
    pawnBackward: false,
    bishopGuardStep: false,
    bishopIgnoreBlock: false,
    knightChain: false,
    knightExtended: false,
    rookDiagonal: false,
    rookArtillery: false,
    globalActions: 0,
    periodicTempo: false,
    cryoPulse: false,
    kingRange: 1,
    kingCaptureActions: 0,
    queenGoldGen: 0,
    flags: new Set<string>(),
    counters: new Map<string, number>(),
  };
}

export function createInitialState(): GameState {
  return {
    round: 0,
    turn: 1,
    boardW: 6,
    boardH: 6,
    pieces: [],
    captureCount: 0,
    deliveredCheck: false,
    actionsLeft: 1,
    queuedActions: 0,
    ownedJokers: [],
    ownedTarots: [],
    ownedPlanets: [],
    ownedVouchers: [],
    upgrades: [],
    objective: "capture_count",
    target: 2,
    turnLimit: 14,
    enemyActions: 1,
    aiDepth: 1,
    aiDifficulty: "Easy",
    gameOver: false,
    lastMove: undefined,
    lastInputSig: "",
    lastInputAt: 0,
    mods: createInitialMods(),
    freezeEnemyPhase: false,
    gold: 0,
    totalChips: 0,
    totalMult: 1,
    roundScore: 0,
    scoreTarget: 100,
    maxTarots: 3,
    shopCards: 3,
    rerollCost: 3,
    baseRerollCost: 3,
    bossActive: false,
    fogOfWar: false,
    pawnImmuneTurns: 0,
    mirrorMods: false,
  };
}
